name: Build Cert-Fixer Zip Archive

on:
  # Triggers the workflow on push events for the "main" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build the final zip file with the correct structure
      - name: Package Module into Zip
        run: |
          # This script assumes your module files are inside a "Cert-Fixer" directory.
          # If they are not, please adjust the path.
          if [ ! -d "Cert-Fixer" ]; then
            echo "::error::'Cert-Fixer' directory not found. Make sure your module files are inside a folder named 'Cert-Fixer' in your repository."
            exit 1
          fi
          
          # Navigate into the directory that contains the module files
          cd Cert-Fixer
          
          # Ensure the required subdirectory exists (this is from your script)
          mkdir -p system/etc/security/cacerts/
          
          # Zip the contents of the current directory into a single file in the parent directory.
          # This ensures that files like 'module.prop' are at the root of the zip.
          echo "Zipping module files into ../Cert-Fixer-Module.zip"
          zip -r ../Cert-Fixer-Module.zip *

      # 3. Upload the single, correctly-structured zip file as a build artifact
      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          # The name of the downloadable artifact file
          name: Cert-Fixer-Module
          # The path to the file we just created
          path: Cert-Fixer-Module.zip
