name: Build Cert-Fixer Zip Archive

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the "main" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Create directory and build the zip file
      #    This step runs inside the Cert-Fixer directory.
      - name: Create Zip Archive
        working-directory: ./Cert-Fixer
        run: |
          echo "Creating required directory structure..."
          mkdir -p system/etc/security/cacerts/
          
          echo "Zipping contents..."
          # The command zips the contents of the current directory ('.')
          # into a file named Cert-Fixer.zip in the parent directory.
          zip -r ../Cert-Fixer.zip .
      
      # 3. Upload the generated zip file as a workflow artifact
      - name: Upload Zip as Artifact
        uses: actions/upload-artifact@v4
        with:
          # The name of the artifact to be uploaded.
          name: Cert-Fixer-Module
          # The path to the file to upload.
          path: Cert-Fixer.zip
